### ISSUE TITLE
end.stamp error Seconds and Days

### ISSUE THREAD

**Issue by williamtellme123** [JohnCoene/graphTweets#1]
> st <- c("hillary", "clinton", "bernie", "sanders", "donald", "trump", "jeb","bush", "ted", "cruz", "marco", "rubio", "carson", "christie")
> presidentialRace <- data.frame()
> for(i in 10:length(st)) {
+         tw <- searchTwitter(st[i], n = 5000, geocode = "39.554883,-99.931641,1000mi")
+         tw <- twListToDF(tw)
+         presidentialRace <- plyr::rbind.fill(presidentialRace, tw)
+     }
> presidentialRace <- presidentialRace[!is.na(presidentialRace$longitude),]
> dyn <- dynamise(data = presidentialRace, tweets = "text", source = "screenName", 
+                       start.stamp = "created", end.stamp = 3600, write = TRUE, 
+                       open = TRUE)

> > Error in dynamise(data = presidentialRace, tweets = "text", source = "screenName",  : 
> >  end.stamp: cannot find columns named '3600' in data

> presidentialRace$date <- as.Date(presidentialRace$created)
> dyn <- dynamise(data = presidentialRace, tweets = "text", source = "screenName", 
+                       start.stamp = "created", end.stamp = 1, write = TRUE, 
+                       open = TRUE)

> > Error in dynamise(data = presidentialRace, tweets = "text", source = "screenName",  : 
> > end.stamp: cannot find columns named '1' in data

**Comment by JohnCoene** [comment]
That is due to poor error checking on my part; pushing a fix and adding tests. Thanks for the notice!
