### ISSUE TITLE
dynamise function error

### ISSUE THREAD

**Issue by BD4Cancer** [JohnCoene/graphTweets#2]
> dyn <- dynamise(tweets, tweets = "text", source = "screenName",
> - time.stamp = "created", write = TRUE, open = TRUE)
>   Error in dynamise(tweets, tweets = "text", source = "screenName", time.stamp = "created",  : 
>   argument inutilisé (time.stamp = "created")

**Comment by JohnCoene** [comment]
The snippet above is from the documentation, which was not up-to-date and ironically unhelpful... Apologies, will push a fix shortly.`time.stamp` as been replaced by `start.stamp` and `end.stamp`, hence `argument inutilisé` error 
`graphTweets::dynamise(data = tweets, tweets = "text", source = "screenName", start.stamp = "created")`

**Comment by BD4Cancer** [comment]
Thank you !
