### ISSUE TITLE
loading dataset

### ISSUE THREAD

**Issue by azraelmt** [JohnCoene/graphTweets#4]
Hi! this is not exactly an issue, but a problem I have found while working with sigma.js

I have my very own dataset in a .csv and .tsv, is there a way to load this sets into the sigma.js graphtweet? i have problems with the hashtag's column. As far my undestading goes, rtweet directly loads the hashtags into the dataframe column, and then it discerns if it's only one hashtag or more (in this latter case, it creates a list with the format c(#xxxxx, #xxxxx)

How could i load my own data with hashtags, considering that the format my hashtags has been saved is [#xxxxx,#xxxxx,#xxxxx]

thanks in advance, and sorry for the broken english!

**Comment by JohnCoene** [comment]
Hi Azrael,

Thank you for opening this issue. Could share with me a sample of the dataset so I can work on supporting such data in {graphTweets}?

**Comment by azraelmt** [comment]
Here are the datasets, I have attached both a .csv and a .tsv as I dont really know which one would be more useful. They contain the most used  metadata in the twinetverse book examples (status_id, screen_name, text, mentions and hashtags).

As you'll see, both the mentions and hashtags columns have the format [#xxxxxx]. In order to give a little more of information, here's what I've tried:

My first attempt was to directly load the hashtags columns to the gt_edges(). This prompted an error that said something among the lines of "expected character vector, not factor object". I tried to solve this by directly converting the column from factor to vector with the function as.vector(). This indeed allowed me to loads the column to the edges but in a wrong way: it loaded the full vector, displaying the hashtags as #[#HashtagOne, #HashtagTwo, #HashtagThree], so it wasnt able to recognize between the various hashtags stored in the array.

I tried to directly alter the format of these hashtags via OpenRefine, to match the way it is stored in R "c(#HashtagOne, HashtagTwo)". This did not work either.

I also tried to export the dataframe that rtweet generates when collecting tweets with search_tweets() to a csv, then loaded said csv to gt_edges(). It prompted the same error i mentioned about the factor object. I pretty much dont know what else to do.

I'll appreciate any feedback on this problem, thanks for the attention!

[datasets_twint.zip](https://github.com/JohnCoene/graphTweets/files/3906007/datasets_twint.zip)

**Comment by JohnCoene** [comment]
Thanks for that.

I will consider including the possibility to do that straight from graphTweets, the package needs some work any how.

Essentially, reproduce the list-column format returned by rtweet using `tidyr::nest`. I hope this helps! 

```r
library(graphTweets)

tweets <- readr::read_csv("~/Downloads/LeBaronFuera.csv", col_type = readr::cols())

# tidy
library(dplyr)

tidy_tweets <- tweets %>% 
  select(screen_name, hashtags) %>% 
  mutate(
    hashtags = gsub("\\[|\\]|'", "", hashtags)
  ) %>% 
  tidyr::separate_rows(hashtags, sep = ", ") %>% 
  tidyr::nest(hashtags = c(hashtags))

g <- tweets %>% 
  gt_edges(screen_name, hashtags) %>% 
  gt_graph()

# github.com/JohnCoene/grapher
grapher::graph(g)
```

Let me know if you want me to explain this further.

**Comment by azraelmt** [comment]
Hi! thanks for your reply!

I really don't know what's the use for tidy_tweets as I dont see where its used. I ran this sample code you provided and it left me with the same issues i was facing at first. I attach my first graph and the one your code makes. As you'll see the same problem appears: multiple hashtags displays when hovering over a node, when the original code from the twinetverse allows to every hashtag to be a distinct entity. 
![screen_shot1](https://user-images.githubusercontent.com/50418516/69888870-c2828100-12b3-11ea-9295-d5313683fbe8.png)
![screen_shot2](https://user-images.githubusercontent.com/50418516/69888871-c2828100-12b3-11ea-9a5f-ea0f50783005.png)

**Comment by JohnCoene** [comment]
Wooops, Apologies! I was too hasty in my reply. 

This works correctly:

```r
library(graphTweets)

tweets <- readr::read_csv("~/Downloads/LeBaronFuera.csv", col_type = readr::cols())

# tidy
library(dplyr)

tidy_tweets <- tweets %>% 
  select(screen_name, hashtags) %>% 
  mutate(
    hashtags = gsub("\\[|\\]|'", "", hashtags)
  ) %>% 
  tidyr::separate_rows(hashtags, sep = ", ") %>% 
  tidyr::nest(hashtags = c(hashtags))

tidy_tweets$hashtags <- tidy_tweets$hashtags %>%  
  purrr::map(unlist) %>% 
  purrr::map(unname)

g <- tidy_tweets %>% 
  gt_edges(screen_name, hashtags) %>% 
  gt_graph()

# github.com/JohnCoene/grapher
grapher::graph(g)
```

**Comment by JohnCoene** [comment]
@azraelmt Did that work?

**Comment by azraelmt** [comment]
Hi! Sorry for the late reply, kinda busy days.

This last snippet of code works perfectly! Thank you so much for your patience and time!
